apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- backstage-deployment.yaml
- backstage-service.yaml
- rbac.yaml

secretGenerator:
- name: postgres-secrets
  literals:
  - POSTGRES_USER=backstage
  - POSTGRES_PASSWORD=backstage
  - POSTGRES_DB=backstage

- name: backstage-secrets
  literals:
  - GITHUB_TOKEN=change-me
  - AUTH_GITHUB_CLIENT_ID=change-me
  - AUTH_GITHUB_CLIENT_SECRET=change-me
